baseurl: https://naierii.github.io/boxxerworld-shopify-frontend/
baseUrl: https://naierii.github.io/boxxerworld-shopify-frontend/
publicpath: https://naierii.github.io/boxxerworld-shopify-frontend/
publicPath: https://naierii.github.io/boxxerworld-shopify-frontend/
url: https://naierii.github.io/boxxerworld-shopify-frontend/
